version: '3'
services:

 db:
    container_name: psql_app
    restart: always
    image: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./config.env
    volumes:
       - db-data:/var/lib/postgres/data
    expose:
      - 5432
    ports:
      - 5432:5432
    tty: true

volumes:
  db-data: